<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace Pot\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>LoginResp</code>
 */
class LoginResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     */
    protected $access_token = '';
    /**
     * Generated from protobuf field <code>int32 expire_in = 2;</code>
     */
    protected $expire_in = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_token
     *     @type int $expire_in
     * }
     */
    public function __construct($data = NULL) {
        \Pot\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 expire_in = 2;</code>
     * @return int
     */
    public function getExpireIn()
    {
        return $this->expire_in;
    }

    /**
     * Generated from protobuf field <code>int32 expire_in = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExpireIn($var)
    {
        GPBUtil::checkInt32($var);
        $this->expire_in = $var;

        return $this;
    }

}

